s: 
   - 90 
   - 14
c:
   d: poisson
   args:
      - 18
      - 1.8
mu:
   d: exponential
   args:
     -
       - 0.198
       - 0.18
     -
       - 0.162
       - 0.18
v: 
   d: exponential
   args:
      - 0.12
      - 0.24
